Repository kubeedge/community, pull requests merged in 2022-09, with the labels that each got.

#106 update security threat model method
  sig-security/sig-security-audit/KubeEdge-threat-model-and-security-protection-analysis.md
Labels: size/XS, lgtm

#81 add self-assessment.md and joint-review.md
  sig-security/assets/kubeedge_arch.png
  sig-security/assets/kubeedge_overview.png
  sig-security/joint-review.md
  sig-security/self-assessment.md
Labels: lgtm, approved, size/XL

#107 add events dir to archive community events
  events/OpenSourcePromotionPlan2020/summer2020-cn.md
  events/OpenSourcePromotionPlan2020/summer2020.md
  events/OpenSourcePromotionPlan2020/tasks_list.md
Labels: size/XS, lgtm, approved
