Repository kubeedge/community, pull requests merged in 2022-10, with the labels that each got.

#108 add TSC documents
  tsc/README.md
  tsc/charter.md
Labels: size/M, lgtm, approved

#115 Use unified folder name prefixes for community components
  commitee-technical-steering/README.md
  commitee-technical-steering/charter.md
  security-team/comms-templates/join-announcement-email-list.md
  sig-ai/Distributed Synergy AI Benchmarking.md
  sig-security/charter.md
  sig-security/joint-review.md
  sig-security/self-assessment.md
  sig-security/sig-security-audit/KubeEdge-threat-model-and-security-protection-analysis.md
  team-security/README.md
  team-security/SECURITY.md
  team-security/comms-templates/distributors-announcement-email.md
  team-security/comms-templates/join-announcement-email-list.md
  team-security/comms-templates/non-vuln-response.md
  team-security/comms-templates/vulnerability-announcement-email.md
  team-security/comms-templates/vulnerability-announcement-issue.md
  team-security/comms-templates/vulnerability-announcement-slack.md
  team-security/images/Vulnerability-handling-process.PNG
  team-security/images/vulnerability-process-timeline.PNG
  team-security/private-distributors-list.md
  team-security/report-a-vulnerability.md
  team-security/security-groups.md
  team-security/security-release-process.md
Labels: lgtm, approved, size/XXL

#109 Add VSLAM-demo example
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/README.md
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/build/edgeslam-run/Dockerfile
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/build/orbslam2-dev/Dockerfile
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/build/orbslam2-dev/ros_entrypoint.sh
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/build/ros-melodic/Dockerfile
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/build/ros-melodic/README.md
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/build/ros-melodic/entrypoint_setup.sh
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/build/ros-melodic/terminator_background.png
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/build/ros-melodic/terminator_config
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/cloud-deployment.yaml
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/edge-deployment.yaml
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/images/results.png
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/scripts/run_container_cloud.sh
  sig-robotics/examples/Implement-VSLAM-algorithm-based-on-KubeEdge/scripts/run_container_edge.sh
  sig-robotics/proposal/Implement-VSLAM-algorithm-based-on-KubeEdge/README.md
  sig-robotics/proposal/Implement-VSLAM-algorithm-based-on-KubeEdge/images/vslam_kubeedge_orbslam2.png
  sig-robotics/proposal/Implement-VSLAM-algorithm-based-on-KubeEdge/images/vslam_kubeedge_proposal_arch.png
  sig-robotics/proposal/Implement-VSLAM-algorithm-based-on-KubeEdge/images/vslam_kubeedge_proposal_design_arch.png
Labels: lgtm, approved, size/XL
