Repository kubeedge/community, pull requests merged in 2023-10, with the labels that each got.

#160 Add owners for community
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#172 Update 2023 Roadmap
  roadmap.md
  roadmap_zh.md
Labels: lgtm, approved

#156 address minor nitpicks and add Micro-ROS as a possible extension.
  sig-robotics/charter.md
Labels: size/M, lgtm, approved

#163 Complete the membership for inactive member
  community-membership.md
Labels: size/M, lgtm, approved

#157 Complete the community governance
  GOVERNANCE.md
  governance_diagram.png
Labels: lgtm, approved, size/L

#169 Add DaoCloud to Private Distributors List
  team-security/security-groups.md
Labels: size/XS, lgtm, approved

#170 add implementation of Generating Action Sequences for Robot Task Plan using LLM
  .gitignore
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/.gitignore
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/.gitmodules
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/Dockerfile
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/README.md
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/bot_description/__init__.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/bot_description/core.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/bot_description/operator.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/bot_description/prompt.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/bot_description/schema.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/bot_description/sensor.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/bot_description/user_client.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/launch/gazebo.launch.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/package.xml
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/requirements.txt
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/resource/bot_description
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/setup.cfg
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/setup.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/test/test_copyright.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/test/test_flake8.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/test/test_pep257.py
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/urdf/bot_base.urdf
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/urdf/bot_gazebo.urdf
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/world/base.world
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/world/bot.world
  sig-robotics/examples/Generating-Action-Sequences-for-Robot-Task-Plans-using-LLM/src/bot_description/world/neighborhood.world
  sig-robotics/proposal/Generating Action Sequences for Robot Task Plans using LLM/README.md
  sig-robotics/proposal/Generating Action Sequences for Robot Task Plans using LLM/images/image_1.png
  sig-robotics/proposal/Generating Action Sequences for Robot Task Plans using LLM/images/image_2.png
  sig-robotics/proposal/Generating Action Sequences for Robot Task Plans using LLM/images/image_3.png
  sig-robotics/proposal/Generating Action Sequences for Robot Task Plans using LLM/images/image_4.png
Labels: lgtm, approved, size/XXL
