Repository kubeedge/community, pull requests merged in 2024-01, with the labels that each got.

#162 add SIG Networking chairs
  sig-networking/README.md
Labels: size/XS, lgtm, approved

#161 Add SIG AI chairs and technical leads
  sig-ai/README.md
Labels: lgtm, approved, size/S

#87 add sig testing charter
  sig-testing/README.md
  sig-testing/charter.md
Labels: size/M, lgtm, approved
